apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "locust-neutron.fullname" . }}-config
  labels:
    {{- include "locust-neutron.labels" . | nindent 4 }}
data:
  config.toml: |-
    {{- toYaml .Values.config.configToml | nindent 4 }}
